version: '2'
services:
  jiotmsapp-app:
    image: jiotmsapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jiotmsapp-mysql:3306/jiotmsapp?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jiotmsapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jiotmsapp-elasticsearch:9200
    ports:
      - 8080:8080
  jiotmsapp-mysql:
    extends:
      file: mysql.yml
      service: jiotmsapp-mysql
  jiotmsapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jiotmsapp-elasticsearch
